### ISSUE TITLE
Re-design DB schema

### ISSUE THREAD

**Issue by alexbojko** [aih/billtitles-py#22]
* Review current DB schema 
* Pull up DB tables with data from [aih/billtitleindex](/aih/billtitleindex) 
* Setup foreign keys between models from [aih/billtitleindex](/aih/billtitleindex)  and models [aih/billtitles-py](https://github.com/aih/billtitles-py/)
* Provide updated DB tables with relations diagram

Proposed solution:
![DB_schema](https://user-images.githubusercontent.com/370714/161739353-cb5b0abf-fa41-4407-9554-d4ff13cccbb7.png)

**Comment by alexbojko** [comment]
@aih could you please verify that the schema is correct?


I also have a question about the bill titles. Now we have 3 tables with `titles`:
* `btiapp_billstagetitle` table
* `btiapp_billtitles` table
* and` titles` table with has m2m relationship with `bill`

Questions:
* I don't see any reason to use m2m relationship between `bill` and `titles`. Each title should be connected with the proper one bill. Each bill may have more than 1 title. I would merge `bill_titles` with `titles` table to avoid using additional joins. (m2m makes sense if 1 title can be connected to more than 1 bill. is it possible?)
* stages vs versions
  * `btiapp_billstagetitle` isn't it the same as title for particular bill from table `bill` with specified version?
  *  I see 2 fields: `bill_titles.is_for_whole_bill`  and `btiapp_billstagetitle.is_for_portion`. Isn't it the same (just opposite boolean values)?
* What does it mean `length` in the `bill` table? 

For testing I used this bill: `billnumber='116hr2500'` in `btiapp_billbasic` table and `billnumber='116hr2500'` in `bill` table.

Here's the metadata collected by billtitleindex app for this bill.

[hr2500.zip](https://github.com/aih/billtitles-py/files/8417593/hr2500.zip)

**Comment by aih** [comment]
Yes, this design is correct, with a few suggestions:

If we can, we should rename the `btiapp_` tables. 'btiapp' is confusing and not necessary.

To your questions:
> I don't see any reason to use m2m relationship between bill and titles. Each title should be connected with the proper one bill. Each bill may have more than 1 title. I would merge bill_titles with titles table to avoid using additional joins. (m2m makes sense if 1 title can be connected to more than 1 bill. is it possible?)

Many bills may have the same title. That is actually part of the reason for having the billtitleindex API. We want to find bills that share the same title, either exactly, or exactly except for the year.

stages vs versions
>stages vs versions
>btiapp_billstagetitle isn't it the same as title for particular bill from table bill with specified version?
>I see 2 fields: bill_titles.is_for_whole_bill and btiapp_billstagetitle.is_for_portion. Isn't it the same (just opposite boolean values)?
>btiapp_billstagetitle isn't it the same as title for particular bill from table bill with specified version?
I think this is correct-- please give me an example of a 'stage'. The 'versions' are like "Introduced in House", with short names 'ih', 'eh', 'enr', 'is', 'es' etc.

>I see 2 fields: bill_titles.is_for_whole_bill and btiapp_billstagetitle.is_for_portion. Isn't it the same (just opposite boolean values)?
Yes, this is correct. 'is_for_portion' is the opposite of 'is_for_whole_bill'. We get the data as 'is_for_portion', so maybe we keep it that way in the tables.

>What does it mean length in the bill table?
This is the length, in characters, of the bill. We measure this during processing in billtitles-py

**Comment by alexbojko** [comment]
### Here are records (not all of them are included here, just to save space on the screen) for one bill in all tables
---
## billtitlesindex app tables

### btiapp_billbasic
| id | bill\_id | bill\_type | number | bill\_number | congress | introduced\_at |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2729 | hr2500-116 | hr | 2500 | 116hr2500 | 116 | 2019-05-02 |

### btiapp_billstagetitle

| id | title | titleNoYear | type | As | is\_for\_portion | bill\_basic\_id |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 5874 | Federal Employee Paid Leave Act | Federal Employee Paid Leave Act | short | passed house | true | 2729 |
| 5875 | Fentanyl Sanctions Act | Fentanyl Sanctions Act | short | passed house | true | 2729 |
| 5876 | Otto Warmbier North Korea Nuclear Sanctions Act of 2019 | Otto Warmbier North Korea Nuclear Sanctions Act | short | passed house | true | 2729 |
| 5877 | REPAY Act | REPAY Act | short | passed house | true | 2729 |
| 5872 | Fair Chance Act | Fair Chance Act | short | passed house | true | 2729 |


### btiapp_billtitles

| id | official\_title | popular\_title | short\_title | bill\_basic\_id |
| :--- | :--- | :--- | :--- | :--- |
| 2729 | To authorize appropriations for fiscal year 2020 for military activities of the Department of Defense, for military construction, and for defense activities of the Department of Energy, to prescribe military personnel strengths for such fiscal year, and for other purposes. | NULL | National Defense Authorization Act for Fiscal Year 2020 | 2729 |

---

## billtitles-py app tables

### bill

id | length | billnumber | version
-- | -- | -- | --
15 | 7905241 | 116hr2500 | pcs
16 | 7903108 | 116hr2500 | eh
1013 | 6118723 | 116hr2500 | rh
11143 | 155074 | 116hr2500 | ih

### bill_titles
| title\_id | bill\_id | is\_for\_whole\_bill |
| :--- | :--- | :--- |
| 1281 | 11143 | false |
| 28089 | 11143 | false |
| 32563 | 11143 | false |
| 37718 | 11143 | false |
| 54420 | 11143 | false |
| 73283 | 11143 | false |
| 74099 | 11143 | false |
| 75675 | 11143 | false |
| 79358 | 11143 | false |
| 83206 | 11143 | false |
| 83287 | 11143 | false |
| 83803 | 11143 | false |
| 85028 | 11143 | false |
| 87692 | 11143 | false |
| 94619 | 11143 | false |
| 101135 | 11143 | false |


### titles

| id | title |
| :--- | :--- |
| 1281 | Santa Ynez Band of Chumash Indians Land Affirmation Act |
| 28089 | Stop Financing of al-Shabaab Act |
| 32563 | Otto Warmbier North Korea Nuclear Sanctions Act |
| 37718 | Fair Chance to Compete for Jobs Act |
| 54420 | Fentanyl Sanctions Act |
| 73283 | White Sands National Park Establishment Act |
| 74099 | Military Construction Authorization Act for Fiscal Year 2020 |
| 75675 | Fair Chance Act |
| 79358 | To authorize appropriations for fiscal year 2020 for military activities of the Department of Defense and for military construction, to prescribe military personnel strengths for such fiscal year, and for other purposes. |
| 83206 | REPAY Act |
| 83287 | National Defense Strategy Implementation Act |
| 83803 | Return Expenses Paid and Yielded Act |
| 85028 | Federal Employee Paid Leave Act |
| 87692 | To authorize appropriations for fiscal year 2020 for military activities of the Department of Defense, for military construction, and for defense activities of the Department of Energy, to prescribe military personnel strengths for such fiscal year, and for other purposes. |
| 94619 | National Defense Authorization Act for Fiscal Year 2020 |
| 101135 | Restore Honor to Service Members Act |

**Comment by aih** [comment]
This is my thinking about the tables, if we can adapt the APIs to handle these changes.

`bill` stays as it is
`billbasic` stays as it is

`titles`: add the field `titleNoYear`, which can be derived from the title field using a function (generally truncate ‘of 2021’, but we may want to update that function in the future).

Combine `bill_titles` with `btiapp_billtitles`, and call the table ‘bill_titles’. It will have the fields:

`id`, `official_title`, `popular_title`, `short_title` and `bill_basic_id`. I think each of the _title fields should be a foreign key to the titles table, if we can.

The `billstagetitle` table is redundant (if we add titleNoYear to the titles table).

**Comment by aih** [comment]
@alexbojko, check if btiapp_billstagetitle includes 'short', 'official', and 'popular'. If so, we don't need those in `btiapp_billtitles`. So to extend my comment above, we can move some of the fields from `btiapp_billtitles` and `btiapp_billstagetitle` to `bill_titles`:

`id`, `bill_id`, `title_id`, `type` (which will include `short`, `popular` and `official`), `as`, `is_for_portion`. We may not be able to figure out the `as` and the `bill_version` for the same title; if that is the case, we don't need the `as` data and can remove that column.

**Comment by alexbojko** [comment]
Thank you for describing. 
It's better to have it here rather than on the paper as I've done.

**Comment by aih** [comment]
We have decided not to re-factor the schema, but instead to keep the two (btiapp and billtitles-py) separate, to avoid regressions.
